# ArgoCD Project: Kyeol Apps
# Saleor ??ë°°í¬???„ë¡œ?íŠ¸

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kyeol-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "KYEOL Saleor Applications"

  # ?ŒìŠ¤ ?ˆí¬ì§€? ë¦¬ ?ˆìš©
  sourceRepos:
    - "https://github.com/YOUR_ORG/kyeol-app-gitops.git"  # TODO: ?¤ì œ ?ˆí¬ë¡?ë³€ê²?

  # ë°°í¬ ?€?? kyeol ?¤ì„?¤í˜?´ìŠ¤ë§?
  destinations:
    - namespace: kyeol
      server: https://kubernetes.default.svc
    - namespace: kyeol-dev
      server: https://kubernetes.default.svc
    - namespace: kyeol-stage
      server: https://kubernetes.default.svc
    - namespace: kyeol-prod
      server: https://kubernetes.default.svc

  # ?´ëŸ¬?¤í„° ë¦¬ì†Œ?? Namespace, ClusterRole ???ˆìš©
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: networking.k8s.io
      kind: IngressClass

  # ?¤ì„?¤í˜?´ìŠ¤ ë¦¬ì†Œ???ˆìš©
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
